env:  
  node: true  
extends:  
  - plugin:@typescript-eslint/recommended  
  - plugin:prettier/recommended  
parser: '@typescript-eslint/parser'  
parserOptions:  
  ecmaVersion: 9
plugins:  
 - '@typescript-eslint'
ignorePatterns: 
 - '*.js'